pendulum_cart:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  base_to_front_left_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_front_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  base_to_front_right_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_front_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  base_to_back_left_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_back_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  base_to_back_right_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_back_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  